// Type declarations for WASM pitch detection module
// Generated by wasm-pack from Rust code

declare module '*/pure_tone_lib.mjs' {
  /**
   * Initialize the WASM module
   * @param input - WASM binary as ArrayBuffer or path to .wasm file
   * @returns Promise that resolves when module is loaded
   */
  export default function init(input?: ArrayBuffer | string): Promise<void>;

  /**
   * Pitch detector using McLeod Pitch Method (MPM)
   * Analyzes audio buffers and returns pitch and clarity
   */
  export class PitchDetector {
    /**
     * Create a new pitch detector
     * @param sample_rate - Audio sample rate in Hz (e.g., 48000)
     * @param buffer_size - Size of audio buffer to analyze (e.g., 4096)
     */
    constructor(sample_rate: number, buffer_size: number);

    /**
     * Process an audio buffer and detect pitch
     * @param buffer - Audio samples as Float32Array
     * @returns Object with pitch (Hz) and clarity (0-1)
     */
    process(buffer: Float32Array): { pitch: number; clarity: number };

    /**
     * Free the WASM memory (call when done using detector)
     */
    free(): void;
  }
}
