// Type definitions for WASM module generated by wasm-bindgen

export class PitchDetector {
  constructor(sampleRate: number, bufferSize: number);
  process(buffer: Float32Array): TunerResult;
  free(): void;
}

export class TunerResult {
  pitch: number;
  clarity: number;
  free(): void;
}

export function initSync(module: WebAssembly.Module | BufferSource): void;

export default function init(module_or_path?: WebAssembly.Module | BufferSource | Promise<any>): Promise<void>;
